# SPDX-FileCopyrightText: 2024 Howetuft
#
# SPDX-License-Identifier: Apache-2.0

name: LuxCoreTools

on:
  push:
    branches:
      - work
  workflow_dispatch:
  release:
    types:
      - published


jobs:
  build_wheels:
    name: Build LuxCoreTools wheel
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository and submodule(s)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Install Hatch
        uses: pypa/hatch@install

      - name: Build wheel
        shell: bash
        run: |
          hatch build

      # Upload artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: pyluxcoretools-wheel
          path: ./dist/*.whl

      # Upload artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: pyluxcoretools-sdist
          path: ./dist/*.tar.gz

  upload_test:
    needs: [build_wheels]
    environment:
      name: testpypi
      url: https://test.pypi.org/p/pyluxcore
    permissions:
      id-token: write
      attestations: write
      contents: read

    runs-on: ubuntu-latest
    if: ${{ github.ref_name }} == 'work'
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true
          verify-metadata: true
          skip-existing: true
